### ISSUE TITLE
Use attrset key instead of package exe

### ISSUE THREAD

**Issue by srid** [Platonic-Systems/mission-control#15]
For a config like,

```nix
          fmt = {
            exec = pkgs.treefmt;
            category = "Dev Tools";
          };
```

mission-control generates `, treefmt`. But we want it to be `, fmt` instead. 

This should also incidentally fix the conflict with an attrset key being the same as one of the shell tools in PATH.

Test in https://github.com/srid/haskell-template/commit/fb9634b22b50f21b196236366c3fdafa967d13c3#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0R55

**Comment by Kranzes** [comment]
Can we use the same type as a flake's `apps.X.program` for consistency?

**Comment by srid** [comment]
@Kranzes How would you write the following if `exec` was of the same type as that of `app.X.program` (which [appears](https://flake.parts/options/flake-parts.html#opt-flake.apps._name_._name_.program) to allow executable path or derivation, but not script)?

https://github.com/Platonic-Systems/mission-control/blob/9acdaa469ebd3c2d6816f8a30c0c217a0da59fe2/example/flake.nix#L17-L20

**Comment by Kranzes** [comment]
i would use a derivation, writeShellScript or something similar. Also make it buildable by CI.

**Comment by srid** [comment]
> make it buildable by CI

We have #23 for that.
