### ISSUE TITLE
`$PWD` always returns the root of the flake

### ISSUE THREAD

**Issue by 7c78** [Platonic-Systems/mission-control#34]
If I `cd` to a sub-directory and run my scripts, `$PWD` will still return the root path of the flake.

**Comment by srid** [comment]
This is by design. You can disable [`cdToProjectRoot`](https://github.com/Platonic-Systems/mission-control/blob/c2f3f0a8dce770c46bfa217270ee5592f3a5ebf5/nix/flake-module.nix#L42) to disable it. I'll document it in README.
